---
version: "3.7"

services:
  jenkins:
    image: mockserver/mockserver
    environment:
      MOCKSERVER_INITIALIZATION_JSON_PATH: /config/jenkins_api_mock.json
    volumes:
      - type: bind
        source: ./datasources/jenkins
        target: /config
        read_only: True
    command: -serverPort 8080

  mysql:
    image: mariadb:latest
    environment:
      MYSQL_DATABASE: kpireport
      MYSQL_USER: kpireport
      MYSQL_PASSWORD: kpireport_pass
      MYSQL_ROOT_PASSWORD: root_pass
    volumes:
      - type: bind
        source: ./datasources/mysql
        target: /docker-entrypoint-initdb.d
        read_only: True

  prometheus:
    image: mockserver/mockserver
    environment:
      MOCKSERVER_INITIALIZATION_JSON_PATH: /config/prometheus_api_mock.json
    volumes:
      - type: bind
        source: ./datasources/prometheus
        target: /config
        read_only: True
    command: -serverPort 9090

  smtp:
    image: mailhog/mailhog:latest
    ports:
      - "127.0.0.1:8025:8025"

  aws:
    image: localstack/localstack
    environment:
      SERVICES: s3
    volumes:
      - type: bind
        source: ./aws
        target: /docker-entrypoint-initaws.d
        read_only: True

  nginx:
    image: nginx:stable
    volumes:
      - type: bind
        source: ../examples/_build
        target: /usr/share/nginx/html
        read_only: True
    ports:
      - "127.0.0.1:8080:80"

  kpireport:
    build:
      context: ..
      args:
        pip_flags: -e
    entrypoint: /bin/bash
    stdin_open: True
    tty: True
    env_file: .env
    volumes:
      - type: bind
        source: ../kpireport
        target: /opt/kpireport/kpireport
      - type: bind
        source: ../setup.cfg
        target: /opt/kpireport/setup.cfg
        read_only: True
      - type: bind
        source: ../examples
        target: /opt/kpireport/examples
        read_only: True
      - type: bind
        source: ../examples/_build
        target: /opt/kpireport/_build
      - type: bind
        source: ${SCP_IDENTITY_FILE}
        target: /root/.ssh/id_rsa
        read_only: True
    depends_on:
      - jenkins
      - mysql
      - prometheus
      - smtp