---
version: "3.7"

services:
  jenkins:
    image: mockserver/mockserver
    environment:
      MOCKSERVER_INITIALIZATION_JSON_PATH: /config/jenkins_api_mock.json
    volumes:
      - type: bind
        source: ./datasources/jenkins
        target: /config
        read_only: True
    command: -serverPort 8080

  mysql:
    image: mariadb:latest
    environment:
      MYSQL_DATABASE: reportcard
      MYSQL_USER: reportcard
      MYSQL_PASSWORD: reportcard_pass
      MYSQL_ROOT_PASSWORD: root_pass
    volumes:
      - type: bind
        source: ./datasources/mysql
        target: /docker-entrypoint-initdb.d
        read_only: True

  prometheus:
    image: mockserver/mockserver
    environment:
      MOCKSERVER_INITIALIZATION_JSON_PATH: /config/prometheus_api_mock.json
    volumes:
      - type: bind
        source: ./datasources/prometheus
        target: /config
        read_only: True
    command: -serverPort 9090

  smtp:
    image: juanluisbaptiste/postfix:latest
    environment:
      SMTP_SERVER: smtp
      SMTP_USERNAME: reportcard
      SMTP_PASSWORD: reportcard_pass
      SERVER_HOSTNAME: reportcard.dev

  reportcard:
    build:
      context: ..
    entrypoint: /bin/bash
    stdin_open: True
    tty: True
    volumes:
      - type: bind
        source: ../reportcard
        target: /opt/reportcard/reportcard
      - type: bind
        source: ../setup.cfg
        target: /opt/reportcard/setup.cfg
        read_only: True
      - type: bind
        source: ../examples
        target: /opt/reportcard/examples
        read_only: True
      - type: bind
        source: ../_build
        target: /opt/reportcard/_build
    depends_on:
      - jenkins
      - mysql
      - prometheus
      - smtp