---
title: CI report

outputs:
  sendgrid:
    plugin: sendgrid
    args:
      email_from: sender@${EMAIL_DOMAIN}
      email_to: ${EMAIL_TO}
  smtp:
    plugin: smtp
    args:
      smtp_host: smtp
      smtp_port: 1025
      image_strategy: remote
      image_remote_base_url: http://localhost:8080/latest
      email_from: sender@reportcard.dev
      email_to:
        - recipient@reportcard.dev
  html:
    plugin: html

datasources:
  jenkins:
    plugin: jenkins
    args:
      host: jenkins:8080
      user: jenkins_user
      api_token: jenkins_token

views:
  app_build_summary:
    plugin: jenkins.build_summary
    title: Problem application builds
    args:
      filters:
        name: -app
  other_builds:
    plugin: jenkins.build_summary
    title: Other builds
    args:
      filters:
        invert: True
        name: -app
