---
datasources:
  db:
    plugin: mysql
    args:
      host: mysql
      user: reportcard
      passwd: reportcard_pass

views:
  # Show a time series of user signups over the report period.
  signups_over_time:
    plugin: plot
    title: New sign-ups
    cols: 4
    args:
      datasource: db
      query: |
        select * from reportcard.signups
        where created_at >= {from} and created_at < {to}
  # Additionally, show a stat indicating how much the total signups have
  # increased (or decreased) in comparison to the previous report period.
  signups_change:
    plugin: single_stat
    cols: 2
    args:
      datasource: db
      query: |
        select count(*) from reportcard.signups
        where created_at >= {from} and created_at < {to}
      comparison_query: |
        select count(*) from reportcard.signups
        where created_at >= date_sub({from} {interval})
          and created_at < {from}
      #comparison_type: percent
      comparison_type: raw
