---
title: Ops report

outputs:
  sendgrid:
    plugin: sendgrid
    args:
      email_from: sender@${EMAIL_DOMAIN}
      email_to: ${EMAIL_TO}
  smtp:
    plugin: smtp
    args:
      smtp_host: smtp
      smtp_port: 1025
      image_strategy: remote
      image_remote_base_url: http://localhost:8080/latest
      email_from: sender@reportcard.dev
      email_to:
        - recipient@reportcard.dev
  html:
    plugin: html

datasources:
  prom:
    plugin: prometheus
    args:
      host: prometheus:9090

views:
  server_load:
    plugin: plot
    title: Load
    args:
      datasource: prom
      query: |
        100 - (avg by(hostname) (irate(node_cpu_seconds_total{mode="idle"}[5m])) * 100
  critical_alerts:
    plugin: prometheus.alert_summary
    title: Critical alerts
    args:
      datasource: prom
      labels:
        severity: critical
  warning_alerts:
    plugin: prometheus.alert_summary
    title: Warnings
    args:
      datasource: prom
      show_timeline: False
      labels:
        severity: warning
