name: Build documentation

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.x
      uses: actions/setup-python@v1
      with:
        python-version: "3.x"

    - name: Install tox
      run: pip install tox

    - name: Generate example output
      run: |
        touch $SCP_IDENTITY_FILE

        ./dev/run.sh -c examples/mysql.yaml
        ./dev/run.sh --no-rebuild -c examples/jenkins.yaml
        ./dev/run.sh --no-rebuild -c examples/prometheus.yaml
      env:
        SCP_IDENTITY_FILE: /tmp/dummy_scp_identity_file

    - name: Archive examples
      uses: actions/upload-artifact@v1
      with:
        name: examples
        path: examples/_build

    - name: Trigger ReadTheDocs build
      run: |
        api_base=https://readthedocs.org/api/v3
        curl -Ssf --data-binary '' \
          -H "Authorization: Token $READTHEDOCS_API_TOKEN" \
          "$api_base/projects/kpi-reporter/versions/latest/builds/"
      env:
        READTHEDOCS_API_TOKEN: ${{ secrets.READTHEDOCS_API_TOKEN }}
