---
  name: Lint codebase

  on:
    push:
      branches: [master]
    pull_request:
      branches: [master]

  jobs:
    build:
      name: Lint codebase
      runs-on: ubuntu-latest

      steps:
        - uses: actions/checkout@v2

        - name: Lint codebase
          uses: docker://github/super-linter:v3
          env:
            VALIDATE_ALL_CODEBASE: true
            # TODO: turn this back on when it's clear how to get flake8 to
            # OK the type annotations in use; possibly the type annotations
            # are bad.
            VALIDATE_PYTHON_FLAKE8: false
            # Disable linting of templates; the linter does not understand
            # the template syntax nor the fact that some are used as partials.
            VALIDATE_MD: false
            VALIDATE_HTML: false
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
