name: Test trigger

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Trigger ReadTheDocs build
      run: |
        curl -Ssf -X POST -d'' \
          -H "Authorization: Token $READTHEDOCS_API_TOKEN" \
          "https://readthedocs.org/api/v3/projects/kpi-reporter/versions/latest/builds/"
      env:
        READTHEDOCS_API_TOKEN: ${{ secrets.ReadTheDocsAPIToken }}